// !!! This is a file automatically generated by hipify!!!
#pragma once

#include <hip/hip_runtime.h>
#include <hip/hip_runtime.h>
#include <hip/hip_fp16.h>

#include <c10/macros/Export.h>

// Use TORCH_HIP_CPP_API or TORCH_HIP_API for exports from this folder
