// !!! This is a file automatically generated by hipify!!!
#pragma once

#include <ATen/hip/CachingHostAllocator.h>

namespace at::cuda {

inline TORCH_HIP_CPP_API at::HostAllocator* getPinnedMemoryAllocator() {
  return at::getHostAllocator(at::kCUDA);
}
} // namespace at::cuda
