// !!! This is a file automatically generated by hipify!!!
#include <gtest/gtest.h>

#include <ATen/ATen.h>
#include <ATen/hip/impl/HIPCachingAllocatorMasqueradingAsCUDA.h>

#include <ATen/test/allocator_clone_test.h>

TEST(AllocatorTestCUDA, test_clone) {
  test_allocator_clone(c10::hip::HIPCachingAllocatorMasqueradingAsCUDA::get());
}
