// !!! This is a file automatically generated by hipify!!!
#include <gtest/gtest.h>

#include <ATen/hip/HIPContext.h>
#include <ATen/hip/HIPDevice.h>

TEST(CudaDeviceTest, getDeviceFromPtr_fails_with_host_memory) {
  if (!at::cuda::is_available()) {
    return;
  }

  int dummy = 0;

  ASSERT_THROW(at::cuda::getDeviceFromPtr(&dummy), c10::Error);
}
