// !!! This is a file automatically generated by hipify!!!
// Just a little test file to make sure that the HIP library works

#include <c10/hip/HIPException.h>
#include <c10/hip/impl/HIPTest.h>

#include <hip/hip_runtime.h>

namespace c10::hip::impl {

static bool has_hip_gpu() {
  int count = 0;
  C10_HIP_IGNORE_ERROR(hipGetDeviceCount(&count));

  return count != 0;
}

int c10_hip_test() {
  int r = 0;
  if (has_hip_gpu()) {
    C10_HIP_CHECK(hipGetDevice(&r));
  }
  return r;
}

} // namespace c10::hip::impl
