#!/usr/bin/env bash
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Wipe generated run state for the DeepSpeed suites so the next run starts clean.
# Mode is now a single script arg (single|multi write into the same roots):
#   fault    -> fault/report1        (per-baseline subdirs, incl. *_multigpu)
#   e2e      -> e2e/report1          (per-method subdirs, incl. *_multigpu)
#   overhead -> overhead/report1     (single) + overhead/report1_multigpu (multi)
# Also wipe ephemeral checkpoint scratch: each run's cleanup trap already removes it,
# but a crashed/killed run can leave some behind.
#   fault/ckpt, e2e/ckpt
# Summary CSVs (ds_*_summary.csv) are regenerated by extract_ds_perf.py and are left
# in place (matching vllm_script/clean_reports.sh).
rm -rf \
  "${SCRIPT_DIR}/fault/report1" \
  "${SCRIPT_DIR}/e2e/report1" \
  "${SCRIPT_DIR}/overhead/report1" \
  "${SCRIPT_DIR}/overhead/report1_multigpu" \
  "${SCRIPT_DIR}/fault/ckpt" \
  "${SCRIPT_DIR}/e2e/ckpt"

echo "Cleaned DeepSpeed fault + e2e + overhead reports (and checkpoint scratch)."
